datastore:
    build: datastore
    volumes:
        - /data
    command: /bin/sh
    stdin_open: true
monetdb:
    build: monetdb
    ports:
      - "50001:50000"
    volumes_from:
      - datastore
    stdin_open: true
rig:
    build: rig
    ports:
      - "8787:8787"
    links:
      - monetdb
