datastore:
    build: datastore
    volumes:
        - /data
    command: /bin/sh
    stdin_open: true
monetdb:
    build: monetdb
#    image: monetdb/monetdb-r-docker
    ports:
      - "50001:50000"
    volumes_from:
      - datastore
    stdin_open: true
rstudio:
    image: rocker/rstudio
    ports:
      - "8787:8787"
    links:
      - monetdb
